### ISSUE TITLE
is there a specific type of led strip that i can use to extend the strip?

### ISSUE THREAD

**Issue by joshua-pe** [VinzzB/LifxZoneStrip#1]
Instead of building a controller can I just use the led strip and connect it to the z controller?

**Comment by VinzzB** [comment]
I do not own an original Lifx Z strip. I only have some of their light bulbs and tiles. 
I assume a proprietary protocol is in play to communicate with their led strips. not sure though...
If this is the case then you cannot use an APA102 (or any other) leds strip to expand your original Lifx Z strip.
